# Generated by Django 6.0 on 2026-03-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0003_remove_patientvital_blockchain_tx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvital',
            name='blockchain_tx',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='patientvital',
            name='record_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
