# Generated by Django 6.0 on 2026-03-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0004_patientvital_blockchain_tx_patientvital_record_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='patient_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
