# Generated by Django 5.2 on 2026-03-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0005_userprofile_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='patient_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
